### ISSUE TITLE
Roadmap.

### ISSUE THREAD

**Issue by Xithrius** [Xithrius/reddit-tui#1]
- [ ] Show posts in some community from Reddit.
- [ ] Be able to open posts either in a different window in the terminal, or in the browser.
- [ ] Sort posts in different ways (hot, top, new, etc.)
- [ ] Swap between different communities easily.
- [ ] View specific users.

**Comment by Xithrius** [comment]
I'm trying this again.

**Comment by Xithrius** [comment]
Nevermind. I'd rather not.
